Add postfix and nginx scripts and a few updates

diff --git a/mysql_admin b/mysql_admin
--- a/mysql_admin
+++ b/mysql_admin
@@ -1,6 +1,7 @@
 #!/bin/sh
 # 01/19/17 - Created by Andrew Puckett
 # 03/02/17 - Changed to getopts style options and added other improvements, integrated user creation
+# 09/08/17 - Fixed a few user creation bugs, added cron script
 
 MYSQL_OPTS="--add-drop-table --add-locks --create-options --dump-date --extended-insert --no-create-db --quick --quote-names --routines --single-transaction --triggers --tz-utc"
 
@@ -25,6 +26,8 @@ if [ $# -lt 2 ]; then
 	echo "  Import/Export"
 	echo "	-b"
 	echo "		Number of backups to keep. Any backups of the database in the directory more than b days old will be removed."
+	echo "	-c"
+	echo "		Setup daily cron job. Only used with -m option"
 	echo "	-d"
 	echo "		Directory to use. If not present the current directory is used."
 	echo "	-e"
@@ -32,17 +35,21 @@ if [ $# -lt 2 ]; then
 	echo "	-i"
 	echo "		Import mode. Will import gzip'd files."
 	echo "	-o"
-	echo "		Extra options to pass to mysqldump on export. Will be appended to $MYSQL_OPTS. e.g. --no-data"
+	echo "		Extra options to pass to mysqldump on export. Will be appended to \$MYSQL_OPTS. e.g. --no-data"
 	echo "	-r"
 	echo "		Will replace an existing database if present on import."
 	echo
 	echo "  Users"
-	echo "	-c"
-	echo "		Save the new user to the login-path. Only used with -m option"
 	echo "	-l"
 	echo "		Name of Linux user to grant access to users file. Only used with -m option"
 	echo "	-m"
 	echo "		Name of new MySQL user to create."
+	echo "	-p"
+	echo "		Save the new user to the login-path. Only used with -m option"
+	echo "	-q"
+	echo "		Create a new random password for the user. Only used with -m option"
+	echo "	-s"
+	echo "		Echo the password silently. For use in interfacing with other scripts. Only used with -q option"
 	echo
 	echo "AUTHOR"
 	echo "	Andrew Puckett"
@@ -51,16 +58,18 @@ if [ $# -lt 2 ]; then
 fi
 
 BACKUPS=0
-CONFIG=0
+CRON=0
+LOGIN_PATH=0
+CREATE_PASS=0
 EXPORT=0
 IMPORT=0
+SILENT=0
 
-while getopts b:cd:ef:h:il:m:n:o:ru: opt
+while getopts b:cd:ef:h:il:m:n:o:pqrsu: opt
 do
-	case "$opt"
-	in
+	case "$opt" in
 		b) BACKUPS=$OPTARG;;
-		c) CONFIG=1;;
+		c) CRON=1;;
 		d) DIR=$OPTARG;;
 		e) EXPORT=1;;
 		f) FILE=$OPTARG;;
@@ -70,10 +79,15 @@ do
 		m) MYSQL_USER=$OPTARG;;
 		n) DB_NAME=$OPTARG;;
 		o) MYSQL_ADD_OPTS=$OPTARG;;
+		p) LOGIN_PATH=1;;
+		q) CREATE_PASS=1;;
 		r) REPLACE="IF NOT EXISTS";;
+		s) SILENT=1;;
 		u) DB_USER=$OPTARG;;
 	esac
 done
+
+[ $SILENT -eq 1 ] && exec 3>&1 1> /dev/null 2>&1
 
 MYSQL_OPTS="--add-drop-table --add-locks --create-options --dump-date --extended-insert --no-create-db --quick --quote-names --routines --single-transaction --triggers --tz-utc $MYSQL_ADD_OPTS"
 [ -n "$DB_HOST" ] || DB_HOST=localhost
@@ -87,6 +101,7 @@ else
 		echo "ERROR: You must include either a file with the -f option or a user with the -u option" >&2 && exit 1
 	fi
 fi
+[ -z "$DB_NAME" ] && echo "ERROR: You must include a database name." >&2 && exit 1
 
 i=0
 if [ $IMPORT -eq 1 ]; then
@@ -111,7 +126,7 @@ elif [ $EXPORT -eq 1 ]; then
 	echo "Dumping tables into separate SQL command files for database '$DB_NAME' into $EXPORT_DIR"
 
 	for t in $TABLES
-	do 
+	do
 		echo "DUMPING TABLE: $DB_NAME.$t"
 		mysqldump $CONNECT_STRING $MYSQL_OPTS $DB_NAME $t | sed -e 's/DEFINER[ ]*=[ ]*`[^*]*`@`[^*]*`/DEFINER=CURRENT_USER/g' | gzip > $EXPORT_DIR/$t.sql.gz
 		i=$((i+1))
@@ -121,23 +136,30 @@ elif [ $EXPORT -eq 1 ]; then
 fi
 
 if [ $BACKUPS -gt 0 ]; then
-	[ -n "$DIR" ] || DIR=.
-	find $DIR/${DB_NAME}_mysql_* -type d -mtime +$BACKUPS -exec rm -r {} +
+	[ -n "$DIR" ] && DIR=$(dirname $DIR) || DIR=.
+	find $DIR/* -type d -mtime +$BACKUPS -exec rm -r {} +
 fi
 
 if [ -n "$MYSQL_USER" ]; then
-	mysql $CONNECT_STRING -NBA -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" || exit 1
+	mysql $CONNECT_STRING -NBA -e "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;" || exit 1
 
-	st=$(stty -g)
-	#trap "stty $st; exit" HUP INT QUIT TERM
-	stty -echo
-	read -p "$MYSQL_USER password: " MYSQL_PASS
-	stty $st
-	echo
+	if [ $CREATE_PASS -eq 1 ]; then
+		MYSQL_PASS=$(openssl rand -base64 16 | tr / +)
+		echo "####################################################################################################"
+		[ $SILENT -eq 0 ] && echo $MYSQL_USER password: $MYSQL_PASS || echo $MYSQL_PASS | tee /dev/fd/3
+		echo "####################################################################################################"
+	else
+		st=$(stty -g)
+		#trap "stty $st; exit" HUP INT QUIT TERM
+		stty -echo
+		read -p "$MYSQL_USER password: " MYSQL_PASS
+		stty $st
+		echo
+	fi
 
-	mysql $CONNECT_STRING -NBA -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}' WITH GRANT OPTION;"
-	
-	[ $CONFIG ] && mysql_config_editor set --login-path=${DB_HOST}-$MYSQL_USER --host=$DB_HOST --user=$MYSQL_USER --password --skip-warn
+	mysql $CONNECT_STRING -NBA -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASS}' WITH GRANT OPTION;"
+
+	[ $LOGIN_PATH -eq 1 ] && mysql_config_editor set --login-path=${DB_HOST}-$MYSQL_USER --host=$DB_HOST --user=$MYSQL_USER --password --skip-warn
 	if [ -w "/etc/mysql" ]; then
 		cat > /etc/mysql/${DB_NAME}-$MYSQL_USER.cnf <<- EOM
 			[client]
@@ -151,5 +173,15 @@ if [ -n "$MYSQL_USER" ]; then
 
 		[ -n "$USER_NAME" ] && chown $USER_NAME:$USER_NAME /etc/mysql/${DB_NAME}-$MYSQL_USER.cnf
 		chmod 0600 /etc/mysql/${DB_NAME}-$MYSQL_USER.cnf
+	fi
+
+	if [ $CRON -eq 1 ]; then
+		cat > /etc/cron.daily/mysql_dump_$DB_NAME <<- EOM
+			#! /bin/sh
+			{
+			mysql_admin -e -f /etc/mysql/${DB_NAME}-$MYSQL_USER.cnf -n $DB_NAME -d /var/backups/${DB_NAME}_mysql/\$(date +%Y%m%d%H%M%S) -b 30
+			} | logger -t $(basename "$0")
+		EOM
+		chmod +x /etc/cron.daily/mysql_dump_$DB_NAME
 	fi
 fi
